#!/bin/bash

echo "🔧 Configuración de Firebase Storage"
echo "=================================="
echo ""
echo "❌ ERROR DETECTADO: Firebase Storage no está habilitado"
echo ""
echo "🚀 SOLUCIÓN RÁPIDA:"
echo ""
echo "1. Ve a Firebase Console:"
echo "   https://console.firebase.google.com/project/domino-federation/storage"
echo ""
echo "2. Haz clic en 'Get started' o 'Comenzar'"
echo ""
echo "3. Selecciona tu región (recomendado: us-central1)"
echo ""
echo "4. Acepta términos y haz clic en 'Done'"
echo ""
echo "5. Ve a la pestaña 'Rules' y pega estas reglas:"
echo ""
echo "rules_version = '2';"
echo "service firebase.storage {"
echo "  match /b/{bucket}/o {"
echo "    match /profile-images/{userId} {"
echo "      allow read: if request.auth != null;"
echo "      allow write, delete: if request.auth != null"
echo "                           && request.auth.uid == userId"
echo "                           && isValidImageUpload();"
echo "    }"
echo "  }"
echo "}"
echo ""
echo "function isValidImageUpload() {"
echo "  return request.resource != null"
echo "         && request.resource.size < 5 * 1024 * 1024"
echo "         && request.resource.contentType.matches('image/.*');"
echo "}"
echo ""
echo "6. Haz clic en 'Publish'"
echo ""
echo "7. Reinicia el servidor: npm run dev"
echo ""
echo "✅ ¡La funcionalidad de imágenes funcionará perfectamente!"
